### ISSUE TITLE
linker issue on arm64

### ISSUE THREAD

**Issue by petro2050** [drasticactions/Drastic.SDWebImage#1]
Hello,

I found your nuget while searching for a .NET6-compatible SDWebImage library. I'm unable to build my solution due to the following error:

```
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.1.1481/targets/Xamarin.Shared.Sdk.targets(3,3): Error: clang++ exited with code 1:
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_FLAnimatedImage", referenced from:
      objc-class-ref in registrar.o
  "_OBJC_CLASS_$_FLAnimatedImageView", referenced from:
      objc-class-ref in registrar.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation) (MyProject)
```

Could you please check if arm64 support works as intended?

My `info.plist` file looks like this:

```
<key>UIRequiredDeviceCapabilities</key>
<array>
    <string>arm64</string>
</array>
```

My linker behavior is set to `Link Framework SDKs only`. I tried the other options with no luck.

**Comment by Sevenish** [comment]
Ran into the same issue. It seems the ApiDefinitions are out of date.  
`FLAnimatedImage`, `FLAnimatedImageView `and `FLAnimatedImageView_WebCache `are not found in the sharpie generated version in `SDWebWebImage.Binding\ApiDefinitions.cs`

On the original SBWebImage repo you can read what happend:

> FLAnimatedImage integration has its own dedicated repo
> In order to clean up things and make our core project do less things, we decided that the FLAnimatedImage integration does not belong here. From 5.0, this will still be available, but under a dedicated repo [SDWebImageFLPlugin](https://github.com/SDWebImage/SDWebImageFLPlugin).

You can comment them these classes out in `Drastic.SBWebImage/ApiBindings.cs` rebuild and the problem goes away

**Comment by drasticactions** [comment]
Yes, they are. I had only used this for a one off test project so I didn't depend on the linker, so it never hit that. Doing another test project where I do need to deploy to device, it threw. Oops.

https://www.nuget.org/packages/Drastic.SDWebImage/1.0.7

It should be fixed now, with an updated SDWebImage as well. I also updated the readme to make it clear that this is unsupported. If you need this, you should fork it.
